spring:
  cloud:
    gateway:
      routes:
      - id: orderservice
        uri: http://localhost:8081/
        predicates:
        - Path=/order/**
      - id: customerservice
        uri: http://localhost:8082/
        predicates:
        - Path=/customer/**